insert into cars (make, model, price) values ('Volvo', 'C70', '$26486.17');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg', '$68965.97');
insert into cars (make, model, price) values ('Oldsmobile', 'Aurora', '$52279.89');
insert into cars (make, model, price) values ('Mercury', 'Sable', '$25668.08');
insert into cars (make, model, price) values ('Chevrolet', 'Metro', '$24529.33');
insert into cars (make, model, price) values ('Lexus', 'GS', '$99481.05');
insert into cars (make, model, price) values ('Volvo', 'S90', '$62750.91');
insert into cars (make, model, price) values ('BMW', 'X6', '$23911.26');
insert into cars (make, model, price) values ('Mitsubishi', 'Mirage', '$42577.18');
insert into cars (make, model, price) values ('Honda', 'Accord Crosstour', '$77008.46');
insert into cars (make, model, price) values ('Honda', 'Civic', '$99351.60');
insert into cars (make, model, price) values ('Pontiac', 'Trans Sport', '$14345.96');
insert into cars (make, model, price) values ('Chevrolet', 'Classic', '$84584.08');
insert into cars (make, model, price) values ('Jaguar', 'X-Type', '$82958.69');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '$87731.51');
insert into cars (make, model, price) values ('Suzuki', 'Samurai', '$74243.39');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$20941.40');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '$66694.21');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '$62647.70');
insert into cars (make, model, price) values ('Daewoo', 'Nubira', '$49117.66');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '$54307.93');
insert into cars (make, model, price) values ('BMW', '750', '$83665.96');
insert into cars (make, model, price) values ('Plymouth', 'Colt', '$72669.60');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '$55358.72');
insert into cars (make, model, price) values ('Chevrolet', 'Traverse', '$76358.53');
insert into cars (make, model, price) values ('Mercedes-Benz', 'M-Class', '$66725.40');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '$24186.45');
insert into cars (make, model, price) values ('Alfa Romeo', 'Spider', '$46993.46');
insert into cars (make, model, price) values ('Mercedes-Benz', 'G-Class', '$49100.37');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '$53952.83');
insert into cars (make, model, price) values ('Aston Martin', 'V12 Vantage', '$90035.29');
insert into cars (make, model, price) values ('Audi', 'S5', '$66062.27');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '$41595.39');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix Turbo', '$33158.80');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '$67030.31');
insert into cars (make, model, price) values ('Ford', 'Bronco II', '$22079.79');
insert into cars (make, model, price) values ('Mazda', 'Protege', '$95788.15');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 1500', '$84531.03');
insert into cars (make, model, price) values ('GMC', 'Envoy', '$56799.62');
insert into cars (make, model, price) values ('GMC', 'Yukon', '$21564.51');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '$16179.19');
insert into cars (make, model, price) values ('Hyundai', 'Tucson', '$22151.21');
insert into cars (make, model, price) values ('Lamborghini', 'Countach', '$63742.01');
insert into cars (make, model, price) values ('Audi', '5000S', '$79431.87');
insert into cars (make, model, price) values ('Lexus', 'ES', '$42303.15');
insert into cars (make, model, price) values ('Ford', 'F-Series Super Duty', '$74971.08');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '$32643.22');
insert into cars (make, model, price) values ('Rolls-Royce', 'Ghost', '$82808.51');
insert into cars (make, model, price) values ('Honda', 'Accord', '$28580.36');
insert into cars (make, model, price) values ('BMW', 'M3', '$80201.41');
insert into cars (make, model, price) values ('Lexus', 'SC', '$87629.30');
insert into cars (make, model, price) values ('Chevrolet', 'Blazer', '$52259.91');
insert into cars (make, model, price) values ('Lincoln', 'Continental', '$33942.08');
insert into cars (make, model, price) values ('Chrysler', 'LeBaron', '$91860.86');
insert into cars (make, model, price) values ('Kia', 'Spectra', '$79628.89');
insert into cars (make, model, price) values ('Ford', 'E350', '$98271.52');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '$53037.62');
insert into cars (make, model, price) values ('Saab', '900', '$47488.46');
insert into cars (make, model, price) values ('Geo', 'Tracker', '$88778.35');
insert into cars (make, model, price) values ('Rolls-Royce', 'Ghost', '$46338.34');
insert into cars (make, model, price) values ('Scion', 'tC', '$91373.05');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '$14451.80');
insert into cars (make, model, price) values ('GMC', 'Terrain', '$93927.17');
insert into cars (make, model, price) values ('Cadillac', 'Eldorado', '$86807.45');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '$10790.34');
insert into cars (make, model, price) values ('Plymouth', 'Breeze', '$94738.29');
insert into cars (make, model, price) values ('Lexus', 'ES', '$99669.97');
insert into cars (make, model, price) values ('Audi', 'A5', '$65279.68');
insert into cars (make, model, price) values ('BMW', 'M6', '$20777.23');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '$31377.77');
insert into cars (make, model, price) values ('Lamborghini', 'Murciélago', '$6871.65');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '$85808.32');
insert into cars (make, model, price) values ('Isuzu', 'i-Series', '$39643.42');
insert into cars (make, model, price) values ('Audi', 'S4', '$25276.08');
insert into cars (make, model, price) values ('Ford', 'Ranger', '$91003.49');
insert into cars (make, model, price) values ('Acura', 'NSX', '$15514.64');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$94890.46');
insert into cars (make, model, price) values ('Buick', 'Century', '$33491.15');
insert into cars (make, model, price) values ('Lincoln', 'MKZ', '$53161.93');
insert into cars (make, model, price) values ('Subaru', 'Outback', '$13787.28');
insert into cars (make, model, price) values ('Geo', 'Metro', '$36276.73');
insert into cars (make, model, price) values ('Mercedes-Benz', 'R-Class', '$75654.63');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$62895.32');
insert into cars (make, model, price) values ('Nissan', 'Altima', '$41725.33');
insert into cars (make, model, price) values ('Mercury', 'Tracer', '$15305.01');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$81338.16');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '$50246.61');
insert into cars (make, model, price) values ('Honda', 'Civic Si', '$87280.86');
insert into cars (make, model, price) values ('Lotus', 'Exige', '$77542.72');
insert into cars (make, model, price) values ('Lotus', 'Exige', '$41026.87');
insert into cars (make, model, price) values ('Daewoo', 'Nubira', '$84572.36');
insert into cars (make, model, price) values ('Oldsmobile', '88', '$40078.68');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '$96102.20');
insert into cars (make, model, price) values ('Isuzu', 'i-370', '$55954.96');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 1500', '$31471.09');
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt SS', '$14577.62');
insert into cars (make, model, price) values ('Toyota', 'Tundra', '$31862.86');
insert into cars (make, model, price) values ('BMW', 'M6', '$6039.66');
insert into cars (make, model, price) values ('Dodge', 'Ram Wagon B250', '$52948.04');
insert into cars (make, model, price) values ('GMC', 'Suburban 1500', '$95990.74');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$14041.05');
insert into cars (make, model, price) values ('Acura', 'TL', '$18027.21');
insert into cars (make, model, price) values ('Dodge', 'Ram', '$91163.76');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '$15571.85');
insert into cars (make, model, price) values ('Audi', '100', '$49083.28');
insert into cars (make, model, price) values ('Plymouth', 'Horizon', '$46576.37');
insert into cars (make, model, price) values ('Mercury', 'Marauder', '$49257.96');
insert into cars (make, model, price) values ('Hyundai', 'Accent', '$7752.75');
insert into cars (make, model, price) values ('Maserati', 'Spyder', '$42156.31');
insert into cars (make, model, price) values ('Ford', 'Freestar', '$57864.24');
insert into cars (make, model, price) values ('Ford', 'Transit Connect', '$58945.85');
insert into cars (make, model, price) values ('Dodge', 'Magnum', '$83954.72');
insert into cars (make, model, price) values ('Subaru', 'Baja', '$89480.13');
insert into cars (make, model, price) values ('Mitsubishi', 'L300', '$22677.84');
insert into cars (make, model, price) values ('Pontiac', 'Torrent', '$24163.66');
insert into cars (make, model, price) values ('Toyota', 'Avalon', '$89889.39');
insert into cars (make, model, price) values ('Pontiac', 'Chevette', '$62580.65');
insert into cars (make, model, price) values ('Toyota', 'Camry', '$10736.30');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '$36129.61');
insert into cars (make, model, price) values ('BMW', '3 Series', '$22210.03');
insert into cars (make, model, price) values ('Bentley', 'Continental Flying Spur', '$17671.02');
insert into cars (make, model, price) values ('Chevrolet', 'Astro', '$45442.47');
insert into cars (make, model, price) values ('Chrysler', 'New Yorker', '$87661.73');
insert into cars (make, model, price) values ('Suzuki', 'SJ', '$22172.46');
insert into cars (make, model, price) values ('Lexus', 'RX Hybrid', '$65065.48');
insert into cars (make, model, price) values ('Ford', 'Aerostar', '$49417.72');
insert into cars (make, model, price) values ('Maserati', 'Biturbo', '$20319.64');
insert into cars (make, model, price) values ('Eagle', 'Vision', '$70146.18');
insert into cars (make, model, price) values ('Nissan', 'Quest', '$77874.89');
insert into cars (make, model, price) values ('Suzuki', 'Daewoo Lacetti', '$24927.82');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '$41558.98');
insert into cars (make, model, price) values ('Lincoln', 'Navigator', '$89390.90');
insert into cars (make, model, price) values ('Ford', 'F-Series', '$41858.43');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '$38102.35');
insert into cars (make, model, price) values ('Audi', 'A3', '$13379.95');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '$34542.26');
insert into cars (make, model, price) values ('Toyota', 'Solara', '$98324.40');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '$97451.81');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '$13829.97');
insert into cars (make, model, price) values ('Land Rover', 'Defender', '$35795.42');
insert into cars (make, model, price) values ('Toyota', 'Tercel', '$12853.48');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '$6932.50');
insert into cars (make, model, price) values ('Infiniti', 'EX', '$22519.70');
insert into cars (make, model, price) values ('Volvo', 'XC70', '$84167.93');
insert into cars (make, model, price) values ('Mercury', 'Sable', '$46023.31');
insert into cars (make, model, price) values ('Ford', 'F-250 Super Duty', '$12523.92');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '$83735.86');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '$33084.39');
insert into cars (make, model, price) values ('Plymouth', 'Grand Voyager', '$23029.19');
insert into cars (make, model, price) values ('Chevrolet', 'Aveo', '$42707.47');
insert into cars (make, model, price) values ('Ford', 'E-Series', '$75524.80');
insert into cars (make, model, price) values ('Lexus', 'LS Hybrid', '$82638.68');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL65 AMG', '$90000.71');
insert into cars (make, model, price) values ('Buick', 'Roadmaster', '$47000.73');
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', '$98303.72');
insert into cars (make, model, price) values ('Kia', 'Sephia', '$32929.62');
insert into cars (make, model, price) values ('Audi', 'A8', '$97589.71');
insert into cars (make, model, price) values ('Mitsubishi', 'L300', '$72365.44');
insert into cars (make, model, price) values ('Pontiac', 'Fiero', '$49577.39');
insert into cars (make, model, price) values ('Porsche', '914', '$31028.15');
insert into cars (make, model, price) values ('Ford', 'GT500', '$11132.78');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '$94387.65');
insert into cars (make, model, price) values ('Nissan', 'Pathfinder Armada', '$82036.15');
insert into cars (make, model, price) values ('Mitsubishi', 'L300', '$80452.96');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '$74500.23');
insert into cars (make, model, price) values ('Scion', 'xB', '$15161.23');
insert into cars (make, model, price) values ('Kia', 'Sorento', '$73495.26');
insert into cars (make, model, price) values ('Lincoln', 'Mark VIII', '$73188.78');
insert into cars (make, model, price) values ('Chrysler', 'Aspen', '$56648.21');
insert into cars (make, model, price) values ('Nissan', 'Titan', '$97694.91');
insert into cars (make, model, price) values ('Audi', '100', '$37921.38');
insert into cars (make, model, price) values ('Lexus', 'RX', '$75790.99');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '$60057.77');
insert into cars (make, model, price) values ('Audi', 'RS4', '$94754.84');
insert into cars (make, model, price) values ('Dodge', 'Viper', '$76016.16');
insert into cars (make, model, price) values ('Porsche', 'Cayenne', '$9156.48');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', '$84216.78');
insert into cars (make, model, price) values ('Buick', 'Coachbuilder', '$64664.39');
insert into cars (make, model, price) values ('Isuzu', 'Trooper', '$47536.07');
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', '$81032.45');
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', '$7387.13');
insert into cars (make, model, price) values ('GMC', 'Savana', '$57182.66');
insert into cars (make, model, price) values ('Aston Martin', 'DB9', '$83474.63');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500 Club', '$71717.50');
insert into cars (make, model, price) values ('Toyota', 'Yaris', '$23870.56');
insert into cars (make, model, price) values ('Lexus', 'SC', '$38798.50');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '$6192.91');
insert into cars (make, model, price) values ('Cadillac', 'Escalade ESV', '$81738.46');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina APV', '$11072.21');
insert into cars (make, model, price) values ('Audi', 'S4', '$45484.93');
insert into cars (make, model, price) values ('Dodge', 'Intrepid', '$63185.10');
insert into cars (make, model, price) values ('Ford', 'Mustang', '$88789.49');
insert into cars (make, model, price) values ('Mercury', 'Montego', '$27594.92');
insert into cars (make, model, price) values ('Mitsubishi', 'Chariot', '$25140.65');
insert into cars (make, model, price) values ('Oldsmobile', 'Bravada', '$12563.53');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$25333.38');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '$67874.50');
insert into cars (make, model, price) values ('Hummer', 'H3', '$23612.10');
insert into cars (make, model, price) values ('Pontiac', 'Torrent', '$71069.36');
insert into cars (make, model, price) values ('BMW', '330', '$76555.61');
insert into cars (make, model, price) values ('Pontiac', 'Monterey', '$46322.02');
insert into cars (make, model, price) values ('Scion', 'xA', '$87983.03');
insert into cars (make, model, price) values ('Mazda', 'CX-7', '$95220.55');
insert into cars (make, model, price) values ('Audi', 'S6', '$63082.16');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$26024.06');
insert into cars (make, model, price) values ('Cadillac', 'SRX', '$62673.98');
insert into cars (make, model, price) values ('Ford', 'F150', '$71124.27');
insert into cars (make, model, price) values ('Ford', 'Escort', '$52982.52');
insert into cars (make, model, price) values ('Cadillac', 'DTS', '$23089.06');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$95591.25');
insert into cars (make, model, price) values ('Ford', 'Tempo', '$6171.90');
insert into cars (make, model, price) values ('Hummer', 'H3T', '$82094.56');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '$67481.72');
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', '$19352.66');
insert into cars (make, model, price) values ('Ford', 'Escort', '$33976.64');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '$96651.35');
insert into cars (make, model, price) values ('Suzuki', 'Verona', '$93147.04');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '$95798.52');
insert into cars (make, model, price) values ('Dodge', 'Shadow', '$33326.23');
insert into cars (make, model, price) values ('Honda', 'Accord', '$94941.36');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '$31941.90');
insert into cars (make, model, price) values ('Land Rover', 'Freelander', '$80376.20');
insert into cars (make, model, price) values ('Pontiac', 'Aztek', '$73471.86');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '$15884.28');
insert into cars (make, model, price) values ('Mercedes-Benz', 'G-Class', '$68852.26');
insert into cars (make, model, price) values ('Volkswagen', 'Fox', '$75852.18');
insert into cars (make, model, price) values ('Mazda', 'CX-7', '$45733.01');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '$58670.25');
insert into cars (make, model, price) values ('Pontiac', 'GTO', '$43793.48');
insert into cars (make, model, price) values ('Ford', 'Laser', '$86286.64');
insert into cars (make, model, price) values ('Infiniti', 'G', '$23308.18');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '$69259.71');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 2500', '$60096.81');
insert into cars (make, model, price) values ('Ford', 'F350', '$55102.36');
insert into cars (make, model, price) values ('Buick', 'Terraza', '$95223.46');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover Evoque', '$32369.31');
insert into cars (make, model, price) values ('GMC', 'Jimmy', '$22891.03');
insert into cars (make, model, price) values ('Toyota', 'Celica', '$38205.80');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '$88217.00');
insert into cars (make, model, price) values ('Kia', 'Amanti', '$32552.33');
insert into cars (make, model, price) values ('Toyota', 'Sequoia', '$90399.83');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '$17189.07');
insert into cars (make, model, price) values ('Ford', 'F-Series', '$66723.23');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '$72366.60');
insert into cars (make, model, price) values ('Lexus', 'LS', '$21050.89');
insert into cars (make, model, price) values ('Porsche', 'Boxster', '$92190.46');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '$38826.60');
insert into cars (make, model, price) values ('Chevrolet', 'Venture', '$43770.44');
insert into cars (make, model, price) values ('Ford', 'Explorer', '$54372.42');
insert into cars (make, model, price) values ('Chevrolet', 'Sportvan G30', '$40594.62');
insert into cars (make, model, price) values ('Honda', 'Passport', '$41507.19');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$74109.38');
insert into cars (make, model, price) values ('Toyota', 'Matrix', '$99504.88');
insert into cars (make, model, price) values ('BMW', 'Z4 M', '$93998.81');
insert into cars (make, model, price) values ('BMW', 'X6', '$19222.22');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '$68463.87');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '$66802.41');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover Evoque', '$7950.51');
insert into cars (make, model, price) values ('Chrysler', 'Imperial', '$18623.42');
insert into cars (make, model, price) values ('Ford', 'F250', '$12378.30');
insert into cars (make, model, price) values ('Mazda', 'B2000', '$39688.14');
insert into cars (make, model, price) values ('Audi', '5000CS', '$21948.38');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '$30996.28');
insert into cars (make, model, price) values ('Hyundai', 'Genesis', '$25219.87');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '$18095.39');
insert into cars (make, model, price) values ('Honda', 'Civic', '$51724.13');
insert into cars (make, model, price) values ('Toyota', 'Sienna', '$99019.12');
insert into cars (make, model, price) values ('Plymouth', 'Horizon', '$36582.76');
insert into cars (make, model, price) values ('Mitsubishi', '3000GT', '$73984.70');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '$50842.62');
insert into cars (make, model, price) values ('Audi', 'Quattro', '$20136.20');
insert into cars (make, model, price) values ('Buick', 'Century', '$46841.04');
insert into cars (make, model, price) values ('Mercury', 'Mariner', '$90650.98');
insert into cars (make, model, price) values ('Mazda', 'Protege', '$99510.35');
insert into cars (make, model, price) values ('Honda', 'Ridgeline', '$15470.04');
insert into cars (make, model, price) values ('Lexus', 'SC', '$87019.89');
insert into cars (make, model, price) values ('Infiniti', 'QX', '$19297.96');
insert into cars (make, model, price) values ('Pontiac', '6000', '$48537.45');
insert into cars (make, model, price) values ('Lincoln', 'Mark LT', '$91905.67');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '$44019.43');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 3500', '$85951.34');
insert into cars (make, model, price) values ('Aston Martin', 'Vantage', '$9427.13');
insert into cars (make, model, price) values ('BMW', 'M3', '$6611.53');
insert into cars (make, model, price) values ('Chevrolet', 'Express', '$35096.51');
insert into cars (make, model, price) values ('BMW', '530', '$8245.72');
insert into cars (make, model, price) values ('Jeep', 'Patriot', '$77931.24');
insert into cars (make, model, price) values ('GMC', 'Vandura G3500', '$76858.38');
insert into cars (make, model, price) values ('Mitsubishi', 'Cordia', '$52642.68');
insert into cars (make, model, price) values ('GMC', 'Savana 3500', '$29771.89');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '$73819.44');
insert into cars (make, model, price) values ('Audi', 'A8', '$85484.18');
insert into cars (make, model, price) values ('Ferrari', 'California', '$58433.67');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '$94152.62');
insert into cars (make, model, price) values ('Acura', 'Legend', '$26472.26');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '$49779.18');
insert into cars (make, model, price) values ('Lincoln', 'Navigator', '$98213.55');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '$29010.28');
insert into cars (make, model, price) values ('BMW', 'X5', '$12440.57');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$66135.25');
insert into cars (make, model, price) values ('Mitsubishi', 'Chariot', '$96848.40');
insert into cars (make, model, price) values ('Chevrolet', 'Beretta', '$87065.00');
insert into cars (make, model, price) values ('Audi', 'Allroad', '$65921.17');
insert into cars (make, model, price) values ('Saab', '9-3', '$33328.51');
insert into cars (make, model, price) values ('Saab', '9000', '$48264.98');
insert into cars (make, model, price) values ('MINI', 'Cooper', '$27408.69');
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', '$62490.42');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '$49319.71');
insert into cars (make, model, price) values ('Oldsmobile', 'Silhouette', '$15900.78');
insert into cars (make, model, price) values ('Jeep', 'Liberty', '$34591.15');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '$45213.37');
insert into cars (make, model, price) values ('Kia', 'Sedona', '$5028.89');
insert into cars (make, model, price) values ('Mitsubishi', 'Outlander', '$72469.50');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '$89134.26');
insert into cars (make, model, price) values ('BMW', '8 Series', '$91180.29');
insert into cars (make, model, price) values ('BMW', '745', '$44242.41');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$57173.99');
insert into cars (make, model, price) values ('Audi', 'A4', '$79111.43');
insert into cars (make, model, price) values ('Infiniti', 'I', '$61377.61');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '$64859.05');
insert into cars (make, model, price) values ('Volvo', 'V70', '$99328.59');
insert into cars (make, model, price) values ('Buick', 'Coachbuilder', '$15661.58');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', '$85544.42');
insert into cars (make, model, price) values ('Chevrolet', 'Prizm', '$64463.14');
insert into cars (make, model, price) values ('GMC', 'Savana 3500', '$54355.88');
insert into cars (make, model, price) values ('Ford', 'Taurus', '$79773.60');
insert into cars (make, model, price) values ('Mazda', '626', '$16308.29');
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', '$88317.72');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '$36942.59');
insert into cars (make, model, price) values ('Lincoln', 'Mark VIII', '$56738.74');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$26530.39');
insert into cars (make, model, price) values ('Honda', 'CR-V', '$77849.36');
insert into cars (make, model, price) values ('Ford', 'E350', '$60893.90');
insert into cars (make, model, price) values ('Lexus', 'GX', '$9161.08');
insert into cars (make, model, price) values ('Ford', 'F250', '$36627.29');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$10761.01');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '$22291.36');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '$26647.75');
insert into cars (make, model, price) values ('GMC', 'Savana 3500', '$47056.36');
insert into cars (make, model, price) values ('Oldsmobile', '88', '$83587.44');
insert into cars (make, model, price) values ('Nissan', '370Z', '$50352.70');
insert into cars (make, model, price) values ('Suzuki', 'SX4', '$23387.01');
insert into cars (make, model, price) values ('Dodge', 'Caravan', '$28352.16');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '$22910.99');
insert into cars (make, model, price) values ('Hummer', 'H2 SUV', '$75592.69');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '$57756.22');
insert into cars (make, model, price) values ('Chevrolet', 'G-Series G30', '$49083.20');
insert into cars (make, model, price) values ('Suzuki', 'XL-7', '$24054.82');
insert into cars (make, model, price) values ('Toyota', 'FJ Cruiser', '$84565.25');
insert into cars (make, model, price) values ('Chevrolet', '3500', '$44574.55');
insert into cars (make, model, price) values ('Aptera', 'Type-1h', '$20200.57');
insert into cars (make, model, price) values ('Mercedes-Benz', 'GL-Class', '$6252.34');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$5473.55');
insert into cars (make, model, price) values ('Buick', 'LeSabre', '$67522.61');
insert into cars (make, model, price) values ('GMC', 'Suburban 2500', '$46567.82');
insert into cars (make, model, price) values ('Pontiac', '6000', '$51085.03');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '$71902.49');
insert into cars (make, model, price) values ('Saab', '9-5', '$33769.46');
insert into cars (make, model, price) values ('Nissan', 'Armada', '$10788.62');
insert into cars (make, model, price) values ('Pontiac', '6000', '$21328.41');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$66857.60');
insert into cars (make, model, price) values ('Ford', 'Explorer', '$59401.99');
insert into cars (make, model, price) values ('Volvo', 'S80', '$92434.90');
insert into cars (make, model, price) values ('Toyota', 'Prius', '$65752.83');
insert into cars (make, model, price) values ('BMW', '325', '$55535.71');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '$44680.87');
insert into cars (make, model, price) values ('Nissan', '240SX', '$53025.73');
insert into cars (make, model, price) values ('Hyundai', 'HED-5', '$36927.49');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '$66572.21');
insert into cars (make, model, price) values ('Audi', '90', '$20269.19');
insert into cars (make, model, price) values ('Honda', 'S2000', '$43326.63');
insert into cars (make, model, price) values ('Subaru', 'SVX', '$41618.17');
insert into cars (make, model, price) values ('Buick', 'Regal', '$76347.07');
insert into cars (make, model, price) values ('Cadillac', 'CTS-V', '$91981.64');
insert into cars (make, model, price) values ('Lexus', 'ES', '$29743.10');
insert into cars (make, model, price) values ('Honda', 'Odyssey', '$75748.24');
insert into cars (make, model, price) values ('Buick', 'Electra', '$85664.60');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '$39845.13');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$72607.49');
insert into cars (make, model, price) values ('Maserati', 'Gran Sport', '$46401.28');
insert into cars (make, model, price) values ('Honda', 'Odyssey', '$72827.15');
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', '$55174.65');
insert into cars (make, model, price) values ('Mazda', 'Mazda3', '$19993.68');
insert into cars (make, model, price) values ('Ford', 'LTD Crown Victoria', '$26132.45');
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', '$60796.65');
insert into cars (make, model, price) values ('Cadillac', 'XLR', '$84523.68');
insert into cars (make, model, price) values ('Buick', 'Skylark', '$12548.22');
insert into cars (make, model, price) values ('Audi', 'A8', '$91864.51');
insert into cars (make, model, price) values ('Mitsubishi', 'Expo', '$87847.49');
insert into cars (make, model, price) values ('Mazda', 'Mazda6', '$22694.16');
insert into cars (make, model, price) values ('Saab', '9-3', '$43130.58');
insert into cars (make, model, price) values ('Acura', 'TL', '$19322.49');
insert into cars (make, model, price) values ('Cadillac', 'DeVille', '$17204.72');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '$88617.38');
insert into cars (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '$29016.27');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '$29323.55');
insert into cars (make, model, price) values ('Mercury', 'Tracer', '$74361.20');
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', '$32073.97');
insert into cars (make, model, price) values ('Toyota', 'Celica', '$52705.64');
insert into cars (make, model, price) values ('Honda', 'Civic GX', '$61702.55');
insert into cars (make, model, price) values ('Kia', 'Sportage', '$46299.48');
insert into cars (make, model, price) values ('Saturn', 'VUE', '$71926.61');
insert into cars (make, model, price) values ('Dodge', 'Intrepid', '$95342.63');
insert into cars (make, model, price) values ('Dodge', 'Charger', '$60858.07');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '$33712.40');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '$27289.04');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '$72859.55');
insert into cars (make, model, price) values ('Buick', 'Skylark', '$29302.41');
insert into cars (make, model, price) values ('Geo', 'Tracker', '$67520.08');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg', '$16897.57');
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', '$84379.70');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '$80326.77');
insert into cars (make, model, price) values ('Mercury', 'Mystique', '$80716.46');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '$59390.73');
insert into cars (make, model, price) values ('Suzuki', 'Aerio', '$27124.13');
insert into cars (make, model, price) values ('Maserati', 'GranTurismo', '$90240.52');
insert into cars (make, model, price) values ('Audi', 'A8', '$72493.01');
insert into cars (make, model, price) values ('BMW', '6 Series', '$34992.18');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '$56160.05');
insert into cars (make, model, price) values ('Chevrolet', 'Sportvan G30', '$80177.12');
insert into cars (make, model, price) values ('Toyota', 'RAV4', '$42680.11');
insert into cars (make, model, price) values ('Ford', 'Econoline E150', '$43299.05');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500 Club', '$53218.52');
insert into cars (make, model, price) values ('Nissan', 'Frontier', '$19747.90');
insert into cars (make, model, price) values ('Chrysler', 'Aspen', '$26088.18');
insert into cars (make, model, price) values ('Chrysler', 'Town & Country', '$10783.86');
insert into cars (make, model, price) values ('Ford', 'Galaxie', '$25045.74');
insert into cars (make, model, price) values ('Mazda', 'Mazda6', '$98519.66');
insert into cars (make, model, price) values ('Ford', 'Escort ZX2', '$22919.00');
insert into cars (make, model, price) values ('Mercedes-Benz', '400E', '$29346.75');
insert into cars (make, model, price) values ('Chrysler', '300M', '$25120.02');
insert into cars (make, model, price) values ('Ford', 'F350', '$84631.42');
insert into cars (make, model, price) values ('Geo', 'Storm', '$56367.00');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '$42943.47');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '$33422.00');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '$7970.66');
insert into cars (make, model, price) values ('GMC', 'Savana 2500', '$85054.80');
insert into cars (make, model, price) values ('Chevrolet', '3500', '$77309.46');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '$83457.17');
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', '$26538.52');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '$67098.10');
insert into cars (make, model, price) values ('MG', 'MGB', '$29956.30');
insert into cars (make, model, price) values ('GMC', 'Yukon', '$89574.66');
insert into cars (make, model, price) values ('Mazda', 'CX-7', '$42266.27');
insert into cars (make, model, price) values ('Isuzu', 'Space', '$86705.64');
insert into cars (make, model, price) values ('Rolls-Royce', 'Ghost', '$5441.97');
insert into cars (make, model, price) values ('Hyundai', 'Genesis Coupe', '$79801.09');
insert into cars (make, model, price) values ('Kia', 'Rio', '$16976.55');
insert into cars (make, model, price) values ('Toyota', 'Tundra', '$57836.97');
insert into cars (make, model, price) values ('Ford', 'Fusion', '$25632.19');
insert into cars (make, model, price) values ('Acura', 'TL', '$72053.82');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$47540.34');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '$19053.84');
insert into cars (make, model, price) values ('Mercury', 'Milan', '$81778.06');
insert into cars (make, model, price) values ('GMC', 'Yukon', '$93738.43');
insert into cars (make, model, price) values ('Porsche', 'Cayman', '$32212.88');
insert into cars (make, model, price) values ('Lexus', 'SC', '$43234.64');
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', '$98418.96');
insert into cars (make, model, price) values ('Ford', 'Bronco', '$79960.00');
insert into cars (make, model, price) values ('BMW', '5 Series', '$45050.51');
insert into cars (make, model, price) values ('Mazda', 'B2000', '$80250.78');
insert into cars (make, model, price) values ('Dodge', 'Sprinter', '$60480.79');
insert into cars (make, model, price) values ('Plymouth', 'Voyager', '$57962.36');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice Classic', '$5781.06');
insert into cars (make, model, price) values ('Chrysler', 'Concorde', '$76614.50');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '$80488.20');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '$62640.40');
insert into cars (make, model, price) values ('Mitsubishi', 'Montero', '$86795.03');
insert into cars (make, model, price) values ('Ford', 'Mustang', '$49272.81');
insert into cars (make, model, price) values ('Jaguar', 'XF', '$67175.12');
insert into cars (make, model, price) values ('Mitsubishi', 'Challenger', '$28086.41');
insert into cars (make, model, price) values ('GMC', 'Savana 1500', '$81164.99');
insert into cars (make, model, price) values ('Bentley', 'Continental Flying Spur', '$31398.46');
insert into cars (make, model, price) values ('Volkswagen', 'Routan', '$57291.91');
insert into cars (make, model, price) values ('Kia', 'Spectra', '$87436.91');
insert into cars (make, model, price) values ('Audi', '5000S', '$31334.92');
insert into cars (make, model, price) values ('Ford', 'Mustang', '$58553.66');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$41030.04');
insert into cars (make, model, price) values ('MINI', 'Cooper Clubman', '$65070.30');
insert into cars (make, model, price) values ('MINI', 'Clubman', '$16146.27');
insert into cars (make, model, price) values ('BMW', 'X5', '$63108.16');
insert into cars (make, model, price) values ('Dodge', 'Ram', '$25599.10');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '$59454.35');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice Classic', '$49887.57');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', '$83298.40');
insert into cars (make, model, price) values ('Jeep', 'Cherokee', '$20942.46');
insert into cars (make, model, price) values ('Kia', 'Carens', '$57806.76');
insert into cars (make, model, price) values ('Mitsubishi', 'Mirage', '$60566.28');
insert into cars (make, model, price) values ('Volvo', 'XC90', '$58990.05');
insert into cars (make, model, price) values ('Ford', 'Aerostar', '$81386.40');
insert into cars (make, model, price) values ('GMC', 'Yukon', '$54841.75');
insert into cars (make, model, price) values ('GMC', '2500 Club Coupe', '$6141.73');
insert into cars (make, model, price) values ('GMC', 'Sonoma Club Coupe', '$39441.31');
insert into cars (make, model, price) values ('Ford', 'Expedition', '$9513.08');
insert into cars (make, model, price) values ('Isuzu', 'i-290', '$42453.70');
insert into cars (make, model, price) values ('Lexus', 'SC', '$56789.64');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '$27135.90');
insert into cars (make, model, price) values ('Mercury', 'Topaz', '$17539.53');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '$20721.29');
insert into cars (make, model, price) values ('GMC', 'Savana', '$48701.10');
insert into cars (make, model, price) values ('Pontiac', 'G6', '$53791.99');
insert into cars (make, model, price) values ('Ford', 'Bronco II', '$47741.96');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '$16015.88');
insert into cars (make, model, price) values ('Ford', 'Focus', '$87954.98');
insert into cars (make, model, price) values ('Aston Martin', 'V8 Vantage', '$11049.01');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$82654.81');
insert into cars (make, model, price) values ('Dodge', 'Durango', '$91498.51');
insert into cars (make, model, price) values ('Volvo', 'V50', '$31335.97');
insert into cars (make, model, price) values ('Pontiac', 'G6', '$68762.13');
insert into cars (make, model, price) values ('Suzuki', 'Swift', '$79386.02');
insert into cars (make, model, price) values ('Buick', 'Reatta', '$49254.39');
insert into cars (make, model, price) values ('BMW', '8 Series', '$90295.40');
insert into cars (make, model, price) values ('Mazda', 'CX-9', '$69765.21');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$89091.57');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg', '$38373.92');
insert into cars (make, model, price) values ('Subaru', 'Tribeca', '$28424.30');
insert into cars (make, model, price) values ('GMC', 'Sierra', '$25868.17');
insert into cars (make, model, price) values ('Suzuki', 'SJ', '$58098.10');
insert into cars (make, model, price) values ('Mitsubishi', 'Diamante', '$77978.03');
insert into cars (make, model, price) values ('Plymouth', 'Grand Voyager', '$46749.01');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '$95375.94');
insert into cars (make, model, price) values ('Chevrolet', 'Uplander', '$99569.26');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '$5100.09');
insert into cars (make, model, price) values ('Acura', 'TSX', '$8340.31');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', '$95633.95');
insert into cars (make, model, price) values ('Toyota', 'Avalon', '$49099.60');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500', '$43819.32');
insert into cars (make, model, price) values ('Lotus', 'Evora', '$17905.35');
insert into cars (make, model, price) values ('Mazda', '626', '$76394.47');
insert into cars (make, model, price) values ('Volvo', 'S80', '$18945.31');
insert into cars (make, model, price) values ('Rolls-Royce', 'Phantom', '$25545.61');
insert into cars (make, model, price) values ('Smart', 'Fortwo', '$41491.28');
insert into cars (make, model, price) values ('Cadillac', 'CTS', '$67635.07');
insert into cars (make, model, price) values ('Ford', 'Windstar', '$45472.94');
insert into cars (make, model, price) values ('Honda', 'Civic', '$46947.53');
insert into cars (make, model, price) values ('Volvo', 'V90', '$35746.46');
insert into cars (make, model, price) values ('Pontiac', 'Vibe', '$71999.96');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '$98246.05');
insert into cars (make, model, price) values ('Pontiac', 'Firebird', '$36112.22');
insert into cars (make, model, price) values ('Honda', 'Accord', '$68347.93');
insert into cars (make, model, price) values ('Maserati', '430', '$68585.03');
insert into cars (make, model, price) values ('Acura', 'Legend', '$98616.22');
insert into cars (make, model, price) values ('Ford', 'Focus', '$73349.76');
insert into cars (make, model, price) values ('Volkswagen', 'R32', '$53807.40');
insert into cars (make, model, price) values ('Saab', '9000', '$96348.09');
insert into cars (make, model, price) values ('Cadillac', 'STS', '$80579.88');
insert into cars (make, model, price) values ('MINI', 'Clubman', '$49851.99');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '$8156.98');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '$74487.72');
insert into cars (make, model, price) values ('Toyota', 'Camry Hybrid', '$29851.99');
insert into cars (make, model, price) values ('Mercedes-Benz', 'R-Class', '$95218.27');
insert into cars (make, model, price) values ('Mitsubishi', 'Truck', '$31143.47');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '$47260.82');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '$70298.07');
insert into cars (make, model, price) values ('Lincoln', 'Navigator', '$41729.25');
insert into cars (make, model, price) values ('GMC', 'Jimmy', '$16543.80');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '$44320.27');
insert into cars (make, model, price) values ('GMC', 'Sierra 1500', '$67285.56');
insert into cars (make, model, price) values ('Dodge', 'D250', '$58455.36');
insert into cars (make, model, price) values ('Ford', 'Explorer', '$63229.82');
insert into cars (make, model, price) values ('Audi', '200', '$48820.80');
insert into cars (make, model, price) values ('Aston Martin', 'V8 Vantage', '$65040.14');
insert into cars (make, model, price) values ('Maserati', 'Spyder', '$99598.85');
insert into cars (make, model, price) values ('Kia', 'Soul', '$79426.51');
insert into cars (make, model, price) values ('Mercury', 'Topaz', '$96031.09');
insert into cars (make, model, price) values ('Chrysler', 'Pacifica', '$79085.57');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '$62572.53');
insert into cars (make, model, price) values ('Saturn', 'S-Series', '$82414.47');
insert into cars (make, model, price) values ('Buick', 'Riviera', '$93989.36');
insert into cars (make, model, price) values ('Porsche', 'Boxster', '$27174.47');
insert into cars (make, model, price) values ('Subaru', 'Forester', '$99384.17');
insert into cars (make, model, price) values ('Toyota', '4Runner', '$29943.41');
insert into cars (make, model, price) values ('Acura', 'TL', '$7484.84');
insert into cars (make, model, price) values ('Isuzu', 'Trooper', '$34803.88');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '$19132.60');
insert into cars (make, model, price) values ('Ford', 'Econoline E150', '$82813.74');
insert into cars (make, model, price) values ('Volkswagen', 'Cabriolet', '$17997.00');
insert into cars (make, model, price) values ('Ford', 'Fusion', '$21035.79');
insert into cars (make, model, price) values ('Volkswagen', 'Passat', '$59907.07');
insert into cars (make, model, price) values ('GMC', 'Sierra 2500', '$34248.90');
insert into cars (make, model, price) values ('Chrysler', '300', '$75016.52');
insert into cars (make, model, price) values ('Dodge', 'Stratus', '$88431.27');
insert into cars (make, model, price) values ('Chevrolet', 'Impala', '$76735.71');
insert into cars (make, model, price) values ('Buick', 'Hearse', '$31798.75');
insert into cars (make, model, price) values ('Ford', 'Excursion', '$64299.50');
insert into cars (make, model, price) values ('GMC', 'Jimmy', '$78219.63');
insert into cars (make, model, price) values ('GMC', 'Yukon', '$47555.53');
insert into cars (make, model, price) values ('Toyota', 'Celica', '$62863.93');
insert into cars (make, model, price) values ('Audi', 'S5', '$35314.65');
insert into cars (make, model, price) values ('Chevrolet', 'TrailBlazer', '$89901.51');
insert into cars (make, model, price) values ('Chrysler', 'Concorde', '$24832.14');
insert into cars (make, model, price) values ('Cadillac', 'CTS', '$57473.72');
insert into cars (make, model, price) values ('Isuzu', 'Hombre', '$91108.02');
insert into cars (make, model, price) values ('Acura', 'TL', '$28513.87');
insert into cars (make, model, price) values ('Chevrolet', 'Metro', '$44949.44');
insert into cars (make, model, price) values ('Chrysler', 'Concorde', '$64048.64');
insert into cars (make, model, price) values ('Chevrolet', 'Astro', '$64721.13');
insert into cars (make, model, price) values ('Mitsubishi', 'Montero', '$15733.45');
insert into cars (make, model, price) values ('Buick', 'Century', '$49251.46');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$28840.47');
insert into cars (make, model, price) values ('Mitsubishi', 'Chariot', '$91525.17');
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', '$64225.40');
insert into cars (make, model, price) values ('Hyundai', 'Santa Fe', '$70448.85');
insert into cars (make, model, price) values ('Ford', 'Ranger', '$98058.28');
insert into cars (make, model, price) values ('BMW', '7 Series', '$60247.33');
insert into cars (make, model, price) values ('Lincoln', 'LS', '$87484.61');
insert into cars (make, model, price) values ('Chevrolet', 'Corvair', '$54518.99');
insert into cars (make, model, price) values ('Lincoln', 'MKX', '$30890.83');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$18965.18');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '$62379.83');
insert into cars (make, model, price) values ('GMC', 'Envoy', '$27150.87');
insert into cars (make, model, price) values ('Bentley', 'Continental Flying Spur', '$15441.99');
insert into cars (make, model, price) values ('Mazda', 'CX-9', '$8927.16');
insert into cars (make, model, price) values ('Hyundai', 'Accent', '$29407.11');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '$77846.58');
insert into cars (make, model, price) values ('Volkswagen', 'R32', '$93331.68');
insert into cars (make, model, price) values ('Jaguar', 'S-Type', '$12524.52');
insert into cars (make, model, price) values ('Kia', 'Sedona', '$49144.33');
insert into cars (make, model, price) values ('Mitsubishi', 'Diamante', '$96636.03');
insert into cars (make, model, price) values ('Mazda', '626', '$13438.55');
insert into cars (make, model, price) values ('Honda', 'Accord', '$18421.27');
insert into cars (make, model, price) values ('Volvo', 'C70', '$60272.24');
insert into cars (make, model, price) values ('Ford', 'Freestyle', '$71962.72');
insert into cars (make, model, price) values ('Infiniti', 'FX', '$14610.67');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '$94683.69');
insert into cars (make, model, price) values ('Subaru', 'Baja', '$59882.06');
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', '$45592.43');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '$55565.13');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', '$74336.68');
insert into cars (make, model, price) values ('Toyota', '4Runner', '$86672.12');
insert into cars (make, model, price) values ('Chevrolet', 'Astro', '$12353.16');
insert into cars (make, model, price) values ('Ford', 'Aspire', '$80886.08');
insert into cars (make, model, price) values ('Ford', 'Taurus', '$8473.85');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 1500', '$27549.80');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '$77356.57');
insert into cars (make, model, price) values ('Infiniti', 'FX', '$75043.07');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '$77750.26');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$22969.91');
insert into cars (make, model, price) values ('Oldsmobile', 'Silhouette', '$31488.98');
insert into cars (make, model, price) values ('Nissan', 'Quest', '$70659.25');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice', '$27946.45');
insert into cars (make, model, price) values ('Jaguar', 'XK Series', '$73462.63');
insert into cars (make, model, price) values ('Eagle', 'Summit', '$28675.93');
insert into cars (make, model, price) values ('Oldsmobile', 'Alero', '$50535.69');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$77205.84');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '$93233.32');
insert into cars (make, model, price) values ('Porsche', '928', '$20361.98');
insert into cars (make, model, price) values ('Chevrolet', '3500', '$16757.29');
insert into cars (make, model, price) values ('Audi', 'TT', '$87083.07');
insert into cars (make, model, price) values ('Volkswagen', 'Cabriolet', '$72885.26');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '$88901.65');
insert into cars (make, model, price) values ('Oldsmobile', 'Bravada', '$35701.66');
insert into cars (make, model, price) values ('Bentley', 'Arnage', '$71832.25');
insert into cars (make, model, price) values ('Infiniti', 'M', '$78734.02');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '$65695.51');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '$30065.84');
insert into cars (make, model, price) values ('Dodge', 'Avenger', '$84758.25');
insert into cars (make, model, price) values ('Chevrolet', '3500', '$65428.50');
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', '$88972.28');
insert into cars (make, model, price) values ('Ford', 'Ranger', '$22276.28');
insert into cars (make, model, price) values ('Oldsmobile', 'Cutlass Supreme', '$64103.15');
insert into cars (make, model, price) values ('Pontiac', 'Chevette', '$22354.89');
insert into cars (make, model, price) values ('Pontiac', 'Sunfire', '$72745.60');
insert into cars (make, model, price) values ('Nissan', 'Altima', '$14617.07');
insert into cars (make, model, price) values ('Jeep', 'Liberty', '$24869.22');
insert into cars (make, model, price) values ('Eagle', 'Summit', '$85690.60');
insert into cars (make, model, price) values ('BMW', 'X5', '$21812.30');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$87081.54');
insert into cars (make, model, price) values ('Buick', 'LaCrosse', '$13490.09');
insert into cars (make, model, price) values ('Volvo', 'XC90', '$68346.08');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '$95372.19');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '$26167.50');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$20162.28');
insert into cars (make, model, price) values ('Chrysler', 'PT Cruiser', '$46067.27');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice', '$17531.15');
insert into cars (make, model, price) values ('Dodge', 'Ram 2500', '$82325.41');
insert into cars (make, model, price) values ('Mitsubishi', 'Starion', '$96400.07');
insert into cars (make, model, price) values ('Chevrolet', 'Blazer', '$34164.66');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', '$99130.11');
insert into cars (make, model, price) values ('Hyundai', 'XG350', '$58715.46');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '$61721.39');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '$81578.05');
insert into cars (make, model, price) values ('Nissan', 'Sentra', '$45122.02');
insert into cars (make, model, price) values ('Dodge', 'Nitro', '$37820.75');
insert into cars (make, model, price) values ('Hyundai', 'Azera', '$17475.36');
insert into cars (make, model, price) values ('Infiniti', 'Q', '$24616.14');
insert into cars (make, model, price) values ('Mercedes-Benz', 'C-Class', '$56664.81');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$24514.58');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$95145.56');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '$9436.84');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$69146.42');
insert into cars (make, model, price) values ('Geo', 'Prizm', '$30063.02');
insert into cars (make, model, price) values ('Toyota', 'Sienna', '$47387.36');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '$97024.45');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', '$43431.35');
insert into cars (make, model, price) values ('Mitsubishi', 'Precis', '$18539.04');
insert into cars (make, model, price) values ('Subaru', 'XT', '$31202.39');
insert into cars (make, model, price) values ('Mazda', 'MPV', '$70714.89');
insert into cars (make, model, price) values ('Audi', 'A4', '$19668.56');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLS AMG', '$68887.71');
insert into cars (make, model, price) values ('Volkswagen', 'Passat', '$7741.72');
insert into cars (make, model, price) values ('Oldsmobile', 'Bravada', '$16935.66');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '$43501.05');
insert into cars (make, model, price) values ('Ford', 'ZX2', '$36921.77');
insert into cars (make, model, price) values ('Jeep', 'Liberty', '$10734.67');
insert into cars (make, model, price) values ('Jaguar', 'XJ Series', '$27209.03');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '$70461.10');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$96930.07');
insert into cars (make, model, price) values ('Lexus', 'HS', '$48077.59');
insert into cars (make, model, price) values ('Ford', 'E250', '$66190.24');
insert into cars (make, model, price) values ('Nissan', 'Frontier', '$95654.41');
insert into cars (make, model, price) values ('Daewoo', 'Lanos', '$52945.72');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '$15219.32');
insert into cars (make, model, price) values ('Oldsmobile', 'Silhouette', '$91496.97');
insert into cars (make, model, price) values ('Subaru', 'Forester', '$20760.15');
insert into cars (make, model, price) values ('Lexus', 'GX', '$62667.53');
insert into cars (make, model, price) values ('BMW', '760', '$36919.27');
insert into cars (make, model, price) values ('Mercury', 'Sable', '$39718.09');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '$97845.83');
insert into cars (make, model, price) values ('Land Rover', 'Freelander', '$27016.68');
insert into cars (make, model, price) values ('Suzuki', 'XL7', '$61040.24');
insert into cars (make, model, price) values ('Plymouth', 'Laser', '$47059.05');
insert into cars (make, model, price) values ('Lexus', 'RX', '$86297.36');
insert into cars (make, model, price) values ('Mazda', 'Mazdaspeed 3', '$94645.30');
insert into cars (make, model, price) values ('Dodge', 'Avenger', '$22624.22');
insert into cars (make, model, price) values ('Ford', 'Crown Victoria', '$43786.15');
insert into cars (make, model, price) values ('Ford', 'Bronco', '$83652.20');
insert into cars (make, model, price) values ('Ford', 'Bronco', '$49679.98');
insert into cars (make, model, price) values ('Jaguar', 'XJ', '$85710.22');
insert into cars (make, model, price) values ('Ford', 'Expedition', '$91302.28');
insert into cars (make, model, price) values ('Ford', 'Explorer Sport Trac', '$27367.75');
insert into cars (make, model, price) values ('Dodge', 'Caravan', '$69190.94');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$57665.00');
insert into cars (make, model, price) values ('Ford', 'F-Series Super Duty', '$41933.36');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '$98378.15');
insert into cars (make, model, price) values ('Buick', 'Park Avenue', '$10495.97');
insert into cars (make, model, price) values ('Mercury', 'Lynx', '$5076.83');
insert into cars (make, model, price) values ('Suzuki', 'SJ', '$97215.86');
insert into cars (make, model, price) values ('GMC', 'Savana 3500', '$49732.82');
insert into cars (make, model, price) values ('GMC', 'Safari', '$99798.51');
insert into cars (make, model, price) values ('Land Rover', 'Freelander', '$23037.15');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '$56957.88');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '$33499.75');
insert into cars (make, model, price) values ('Toyota', 'Prius Plug-in', '$93625.81');
insert into cars (make, model, price) values ('Toyota', 'FJ Cruiser', '$84122.79');
insert into cars (make, model, price) values ('Mazda', '626', '$28561.61');
insert into cars (make, model, price) values ('Subaru', 'Alcyone SVX', '$65781.89');
insert into cars (make, model, price) values ('GMC', 'Rally Wagon 2500', '$44557.52');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado', '$45595.87');
insert into cars (make, model, price) values ('Toyota', 'Celica', '$5970.82');
insert into cars (make, model, price) values ('Ford', 'Laser', '$93989.13');
insert into cars (make, model, price) values ('Ford', 'E-Series', '$90790.83');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '$96189.48');
insert into cars (make, model, price) values ('Jensen', 'Interceptor', '$30359.63');
insert into cars (make, model, price) values ('Volkswagen', 'Eos', '$48420.50');
insert into cars (make, model, price) values ('Ford', 'Mustang', '$79648.38');
insert into cars (make, model, price) values ('Ford', 'F250', '$32681.59');
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', '$40181.52');
insert into cars (make, model, price) values ('Mercedes-Benz', '300TE', '$8714.95');
insert into cars (make, model, price) values ('Mazda', '929', '$81605.75');
insert into cars (make, model, price) values ('Ford', 'F150', '$32647.36');
insert into cars (make, model, price) values ('Oldsmobile', '88', '$76373.23');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '$33011.08');
insert into cars (make, model, price) values ('Land Rover', 'Defender 90', '$80647.23');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '$70453.37');
insert into cars (make, model, price) values ('Ford', 'Mustang', '$32194.68');
insert into cars (make, model, price) values ('Dodge', 'Stratus', '$82763.41');
insert into cars (make, model, price) values ('Chevrolet', 'Cobalt', '$22380.24');
insert into cars (make, model, price) values ('Nissan', '350Z', '$54817.56');
insert into cars (make, model, price) values ('Volvo', 'C70', '$14854.67');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '$91465.38');
insert into cars (make, model, price) values ('Audi', '4000s', '$40789.62');
insert into cars (make, model, price) values ('Chevrolet', 'Caprice', '$7603.50');
insert into cars (make, model, price) values ('Plymouth', 'Colt', '$96431.35');
insert into cars (make, model, price) values ('Dodge', 'Charger', '$68810.58');
insert into cars (make, model, price) values ('Mazda', 'Mazda5', '$83279.93');
insert into cars (make, model, price) values ('Volvo', '940', '$68208.75');
insert into cars (make, model, price) values ('Infiniti', 'QX', '$69004.70');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '$43684.96');
insert into cars (make, model, price) values ('Maybach', '57', '$94274.62');
insert into cars (make, model, price) values ('BMW', 'X6 M', '$48943.55');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '$61595.61');
insert into cars (make, model, price) values ('Dodge', 'Avenger', '$39607.25');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '$30991.94');
insert into cars (make, model, price) values ('Ford', 'F150', '$74139.11');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '$48424.08');
insert into cars (make, model, price) values ('GMC', 'Envoy', '$64765.41');
insert into cars (make, model, price) values ('Chevrolet', 'S10', '$52972.16');
insert into cars (make, model, price) values ('Toyota', 'Camry Hybrid', '$74667.30');
insert into cars (make, model, price) values ('GMC', 'Sonoma Club Coupe', '$55583.28');
insert into cars (make, model, price) values ('GMC', 'Sonoma', '$33250.19');
insert into cars (make, model, price) values ('Lamborghini', 'Gallardo', '$11090.58');
insert into cars (make, model, price) values ('Suzuki', 'SJ', '$40255.28');
insert into cars (make, model, price) values ('Pontiac', 'Turbo Firefly', '$70826.68');
insert into cars (make, model, price) values ('Honda', 'del Sol', '$30855.04');
insert into cars (make, model, price) values ('Mercury', 'Tracer', '$32673.75');
insert into cars (make, model, price) values ('Pontiac', 'Safari', '$86963.55');
insert into cars (make, model, price) values ('GMC', 'Envoy XL', '$23963.98');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '$72881.21');
insert into cars (make, model, price) values ('Toyota', 'Sienna', '$21502.61');
insert into cars (make, model, price) values ('Ford', 'Windstar', '$82984.85');
insert into cars (make, model, price) values ('Ford', 'Econoline E250', '$36121.37');
insert into cars (make, model, price) values ('Ford', 'F-Series', '$76859.54');
insert into cars (make, model, price) values ('Chevrolet', '3500', '$41714.91');
insert into cars (make, model, price) values ('Toyota', 'T100 Xtra', '$30648.28');
insert into cars (make, model, price) values ('Audi', 'Q7', '$35677.95');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg', '$43143.27');
insert into cars (make, model, price) values ('BMW', 'M5', '$90512.79');
insert into cars (make, model, price) values ('Mazda', 'B-Series', '$54949.58');
insert into cars (make, model, price) values ('Plymouth', 'Grand Voyager', '$44714.81');
insert into cars (make, model, price) values ('Chevrolet', 'K5 Blazer', '$19909.06');
insert into cars (make, model, price) values ('Mazda', '929', '$68153.72');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '$30775.64');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '$37490.80');
insert into cars (make, model, price) values ('Buick', 'Electra', '$77651.44');
insert into cars (make, model, price) values ('Pontiac', 'Firebird Trans Am', '$60485.31');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '$89245.10');
insert into cars (make, model, price) values ('Buick', 'LeSabre', '$14382.59');
insert into cars (make, model, price) values ('Infiniti', 'G25', '$23680.75');
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', '$58381.49');
insert into cars (make, model, price) values ('Porsche', 'Cayenne', '$78642.81');
insert into cars (make, model, price) values ('Ford', 'Taurus', '$44471.92');
insert into cars (make, model, price) values ('Oldsmobile', 'Achieva', '$14055.06');
insert into cars (make, model, price) values ('Subaru', 'B9 Tribeca', '$97957.41');
insert into cars (make, model, price) values ('Dodge', 'Charger', '$24768.63');
insert into cars (make, model, price) values ('Toyota', 'Prius', '$60641.07');
insert into cars (make, model, price) values ('Chevrolet', 'Camaro', '$61789.33');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '$30720.94');
insert into cars (make, model, price) values ('Honda', 'Passport', '$30100.07');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500 Club', '$89499.14');
insert into cars (make, model, price) values ('Maybach', '62', '$91500.75');
insert into cars (make, model, price) values ('Audi', 'Q7', '$13199.86');
insert into cars (make, model, price) values ('Toyota', 'Sequoia', '$72980.51');
insert into cars (make, model, price) values ('Plymouth', 'Prowler', '$74064.30');
insert into cars (make, model, price) values ('Mazda', 'MX-3', '$81786.34');
insert into cars (make, model, price) values ('Oldsmobile', 'Silhouette', '$8488.32');
insert into cars (make, model, price) values ('Chrysler', 'Imperial', '$97633.39');
insert into cars (make, model, price) values ('BMW', 'M3', '$57511.52');
insert into cars (make, model, price) values ('Ford', 'F150', '$79251.40');
insert into cars (make, model, price) values ('Volvo', 'V40', '$73656.98');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500', '$49071.72');
insert into cars (make, model, price) values ('Volkswagen', 'Cabriolet', '$73672.54');
insert into cars (make, model, price) values ('Buick', 'LeSabre', '$69270.13');
insert into cars (make, model, price) values ('Chevrolet', 'Metro', '$46502.19');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '$61192.91');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', '$74015.89');
insert into cars (make, model, price) values ('Kia', 'Optima', '$75268.71');
insert into cars (make, model, price) values ('Audi', 'S5', '$56098.39');
insert into cars (make, model, price) values ('Mazda', 'B-Series', '$9602.26');
insert into cars (make, model, price) values ('Mercedes-Benz', 'E-Class', '$93992.27');
insert into cars (make, model, price) values ('Honda', 'Passport', '$97282.24');
insert into cars (make, model, price) values ('Aston Martin', 'Vanquish S', '$64109.01');
insert into cars (make, model, price) values ('Kia', 'Sportage', '$52120.77');
insert into cars (make, model, price) values ('Mazda', 'Mazdaspeed 3', '$15368.59');
insert into cars (make, model, price) values ('Lamborghini', 'Murciélago', '$38005.54');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '$53713.31');
insert into cars (make, model, price) values ('Rolls-Royce', 'Ghost', '$19076.41');
insert into cars (make, model, price) values ('Mazda', '323', '$6674.44');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '$82181.07');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '$27909.41');
insert into cars (make, model, price) values ('Dodge', 'Journey', '$8026.92');
insert into cars (make, model, price) values ('GMC', 'Savana 2500', '$74144.81');
insert into cars (make, model, price) values ('Audi', 'Cabriolet', '$32755.59');
insert into cars (make, model, price) values ('Mercedes-Benz', 'W201', '$17749.08');
insert into cars (make, model, price) values ('Porsche', '911', '$87438.59');
insert into cars (make, model, price) values ('Ford', 'GT', '$19139.38');
insert into cars (make, model, price) values ('Mazda', 'Navajo', '$19998.44');
insert into cars (make, model, price) values ('Rolls-Royce', 'Ghost', '$43015.56');
insert into cars (make, model, price) values ('BMW', '5 Series', '$68293.26');
insert into cars (make, model, price) values ('Buick', 'Roadmaster', '$27202.06');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '$12102.58');
insert into cars (make, model, price) values ('Oldsmobile', 'Intrigue', '$42222.05');
insert into cars (make, model, price) values ('Honda', 'Pilot', '$73981.86');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '$43912.35');
insert into cars (make, model, price) values ('Ford', 'Aerostar', '$9402.27');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$20221.13');
insert into cars (make, model, price) values ('Mitsubishi', 'Outlander', '$63236.36');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$18581.39');
insert into cars (make, model, price) values ('Honda', 'Pilot', '$69031.16');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '$20651.68');
insert into cars (make, model, price) values ('Acura', 'TL', '$23686.41');
insert into cars (make, model, price) values ('Mazda', 'MPV', '$40540.32');
insert into cars (make, model, price) values ('Nissan', 'Quest', '$75026.15');
insert into cars (make, model, price) values ('Volvo', 'S60', '$18842.76');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$41788.52');
insert into cars (make, model, price) values ('Plymouth', 'Grand Voyager', '$15500.88');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '$25864.62');
insert into cars (make, model, price) values ('Chevrolet', 'Prizm', '$59192.91');
insert into cars (make, model, price) values ('Ford', 'Aerostar', '$57701.77');
insert into cars (make, model, price) values ('Hyundai', 'Genesis', '$36801.31');
insert into cars (make, model, price) values ('BMW', 'M6', '$91159.12');
insert into cars (make, model, price) values ('Porsche', 'Boxster', '$36848.47');
insert into cars (make, model, price) values ('Mazda', 'MX-5', '$72569.36');
insert into cars (make, model, price) values ('BMW', 'X5', '$51716.20');
insert into cars (make, model, price) values ('Ford', 'Bronco', '$48763.46');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '$68667.56');
insert into cars (make, model, price) values ('Volvo', 'S60', '$90714.34');
insert into cars (make, model, price) values ('Volkswagen', 'Golf', '$89121.68');
insert into cars (make, model, price) values ('Volkswagen', 'Type 2', '$7347.60');
insert into cars (make, model, price) values ('Maybach', '57', '$72926.54');
insert into cars (make, model, price) values ('Acura', 'Vigor', '$32617.74');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '$17849.97');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$23300.24');
insert into cars (make, model, price) values ('Mazda', 'Familia', '$28340.89');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '$54668.23');
insert into cars (make, model, price) values ('Lexus', 'LX', '$51877.85');
insert into cars (make, model, price) values ('GMC', '1500', '$68758.88');
insert into cars (make, model, price) values ('Volkswagen', 'Cabriolet', '$26167.26');
insert into cars (make, model, price) values ('Ford', 'Edge', '$21662.57');
insert into cars (make, model, price) values ('Chevrolet', 'G-Series G30', '$90004.95');
insert into cars (make, model, price) values ('Mazda', 'MPV', '$37423.70');
insert into cars (make, model, price) values ('Subaru', 'Forester', '$51861.19');
insert into cars (make, model, price) values ('GMC', 'Terrain', '$29024.79');
insert into cars (make, model, price) values ('Kia', 'Sportage', '$42826.06');
insert into cars (make, model, price) values ('Ford', 'Ranger', '$91392.90');
insert into cars (make, model, price) values ('Suzuki', 'Forenza', '$49720.79');
insert into cars (make, model, price) values ('Mercury', 'Sable', '$26051.28');
insert into cars (make, model, price) values ('BMW', '525', '$41326.46');
insert into cars (make, model, price) values ('Dodge', 'Nitro', '$5844.80');
insert into cars (make, model, price) values ('Mercury', 'Grand Marquis', '$44946.06');
insert into cars (make, model, price) values ('Pontiac', 'Vibe', '$14072.66');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$86884.02');
insert into cars (make, model, price) values ('Chevrolet', 'Blazer', '$89899.29');
insert into cars (make, model, price) values ('Toyota', 'Solara', '$50557.50');
insert into cars (make, model, price) values ('Pontiac', 'Grand Am', '$83879.00');
insert into cars (make, model, price) values ('Geo', 'Tracker', '$7429.27');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '$62918.99');
insert into cars (make, model, price) values ('Mitsubishi', 'Pajero', '$61459.54');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 3500', '$39646.90');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '$83615.24');
insert into cars (make, model, price) values ('Ford', 'Excursion', '$34851.73');
insert into cars (make, model, price) values ('Ford', 'Fiesta', '$76983.85');
insert into cars (make, model, price) values ('BMW', '7 Series', '$19695.90');
insert into cars (make, model, price) values ('Kia', 'Sportage', '$44815.64');
insert into cars (make, model, price) values ('Maserati', '430', '$76515.67');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '$6052.92');
insert into cars (make, model, price) values ('Ford', 'F350', '$22847.54');
insert into cars (make, model, price) values ('Kia', 'Optima', '$27863.68');
insert into cars (make, model, price) values ('Honda', 'Accord', '$64052.70');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '$87577.47');
insert into cars (make, model, price) values ('Chevrolet', 'Express 2500', '$98341.43');
insert into cars (make, model, price) values ('Acura', 'ZDX', '$44429.00');
insert into cars (make, model, price) values ('GMC', 'Savana 3500', '$91962.40');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '$36515.30');
insert into cars (make, model, price) values ('Dodge', 'Caravan', '$43609.21');
insert into cars (make, model, price) values ('Pontiac', 'GTO', '$21594.12');
insert into cars (make, model, price) values ('Chevrolet', 'Corsica', '$13420.50');
insert into cars (make, model, price) values ('Chevrolet', 'Monte Carlo', '$54574.02');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '$91412.56');
insert into cars (make, model, price) values ('Chevrolet', 'Uplander', '$78212.13');
insert into cars (make, model, price) values ('Honda', 'Prelude', '$46071.53');
insert into cars (make, model, price) values ('Kia', 'Rio', '$13656.54');
insert into cars (make, model, price) values ('GMC', 'Suburban 2500', '$21109.68');
insert into cars (make, model, price) values ('Chevrolet', 'Tahoe', '$47489.31');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 2500', '$64167.70');
insert into cars (make, model, price) values ('BMW', '3 Series', '$87288.95');
insert into cars (make, model, price) values ('Aptera', 'Typ-1', '$24967.40');
insert into cars (make, model, price) values ('Audi', 'TT', '$59003.46');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '$57132.36');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '$5505.58');
insert into cars (make, model, price) values ('Suzuki', 'SJ', '$32610.12');
insert into cars (make, model, price) values ('Ford', 'Galaxie', '$71107.66');
insert into cars (make, model, price) values ('Lexus', 'IS', '$35270.83');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '$80940.49');
insert into cars (make, model, price) values ('Plymouth', 'Grand Voyager', '$9554.37');
insert into cars (make, model, price) values ('Ford', 'Explorer Sport', '$94592.21');
insert into cars (make, model, price) values ('Maserati', 'GranTurismo', '$90335.43');
insert into cars (make, model, price) values ('Mazda', 'Miata MX-5', '$41662.55');
insert into cars (make, model, price) values ('Volkswagen', 'New Beetle', '$79575.41');
insert into cars (make, model, price) values ('Toyota', 'Camry', '$87360.85');
insert into cars (make, model, price) values ('Acura', 'TL', '$93627.74');
insert into cars (make, model, price) values ('Acura', 'Integra', '$81782.49');
insert into cars (make, model, price) values ('Nissan', 'Cube', '$58393.31');
insert into cars (make, model, price) values ('Daewoo', 'Lanos', '$37070.75');
insert into cars (make, model, price) values ('Maserati', 'Quattroporte', '$8276.58');
insert into cars (make, model, price) values ('Ford', 'Focus', '$86081.02');
insert into cars (make, model, price) values ('Toyota', 'Tacoma Xtra', '$25143.41');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '$61239.12');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '$91593.80');
insert into cars (make, model, price) values ('Mitsubishi', 'Cordia', '$25706.72');
insert into cars (make, model, price) values ('Volvo', 'S60', '$47836.59');
insert into cars (make, model, price) values ('Plymouth', 'Neon', '$39168.23');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '$70644.57');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '$65109.70');
insert into cars (make, model, price) values ('Pontiac', '6000', '$63985.77');
insert into cars (make, model, price) values ('Volvo', 'S80', '$63951.21');
insert into cars (make, model, price) values ('Hyundai', 'Azera', '$90199.60');
insert into cars (make, model, price) values ('Chevrolet', 'Malibu', '$14989.03');
insert into cars (make, model, price) values ('GMC', 'Savana 1500', '$82066.13');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '$26501.69');
insert into cars (make, model, price) values ('Ford', 'Club Wagon', '$13383.18');
insert into cars (make, model, price) values ('Audi', 'TT', '$46166.25');
insert into cars (make, model, price) values ('Isuzu', 'Rodeo', '$45719.70');
insert into cars (make, model, price) values ('Jaguar', 'XK', '$21655.85');
insert into cars (make, model, price) values ('Subaru', 'Leone', '$62741.41');
insert into cars (make, model, price) values ('Toyota', 'Camry', '$33975.36');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CL-Class', '$73654.17');
insert into cars (make, model, price) values ('Ford', 'Falcon', '$12740.22');
insert into cars (make, model, price) values ('GMC', 'Acadia', '$28755.12');
insert into cars (make, model, price) values ('Mitsubishi', 'Lancer', '$30314.72');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 2500', '$44781.20');
